Frontend pages: thymeleaf
GritsH/trpo pull request #14
Opened 2022-11-24 01:29 UTC by NovikVeronika

2022-11-24 04:49 UTC, GritsH requested changes

2022-11-24 04:49 UTC, GritsH commented on src/main/resources/templates/admin_lot_id.html
> +        <form class="admin-lot-id-form" action="#"
Лучше эту и следующую строчку поменять местами в том плане что каждый див лота также является формой

2022-11-24 04:49 UTC, GritsH commented on src/main/resources/templates/admin_lot_id.html
> +                        <button class="delete-lot-button" type="button"
и в таком случае сделать кнопку submit

2022-11-24 04:49 UTC, GritsH commented on src/main/resources/templates/admin_user_id.html
> +            <div class="panel-profile" th:each="user:${allUsers}">
тоже самое что и с лотами

2022-11-24 04:49 UTC, GritsH commented on src/main/resources/templates/active_auctions.html
> +        <div class="panel-active-auctions" th:each="lot : ${allActiveAuctions}">
лучше переименуй lot на auction

2022-11-24 04:49 UTC, GritsH commented on src/main/resources/templates/lot-details.html
> +                    <p class="lot-category" th:text="${categories}">category</p>
category для лота берется из него же. лит categories отправляется тебе для дроп дауна в хедере

2022-11-24 04:49 UTC, GritsH commented on src/main/resources/templates/lot-details.html
> +                            th:href="@{/active-auctions/lot/{id}(id=${foundAuction.lot.id})/participate}">
сделай это формой и кнопкуу поменяй на submit

2022-11-24 04:49 UTC, GritsH commented on src/main/resources/templates/admin_lot_id.html
> +            <div class="panel-lot" th:each="lot:${activeAuctions}">
переименую lot на auction

2022-11-24 04:56 UTC, GritsH commented
также не вижу изменений в нейминге страниц

2022-11-25 19:10 UTC, NovikVeronika commented on src/main/resources/templates/lot-details.html
> +                    <p class="lot-category" th:text="${categories}">category</p>
в лоте нет поля category

2022-11-26 04:46 UTC, GritsH commented on src/main/resources/templates/lot-details.html
> +                    <p class="lot-category" th:text="${categories}">category</p>
в лоте есть itemType

2022-11-26 05:00 UTC, GritsH requested changes

2022-11-26 05:03 UTC, GritsH commented
1. description категорий смотри в itemType enum'е 
2. жду цикла для дроп дауна категорий в хэдере и таймлиф к ним
3. еще не все страницы переименованы

2022-11-27 05:35 UTC, GritsH requested changes

2022-11-27 05:35 UTC, GritsH commented on src/main/resources/templates/jewelry-page.html
> +                    <input class="jewelry-precious-stones" id="jewelryPreciousStone" type="text"
в класе лот это поле является boolean, то есть либо да либо нет и надо наверно поменять это с текста на селект

2022-11-27 05:35 UTC, GritsH commented on src/main/resources/templates/furniture-page.html
> +                    <select class="furniture-speciality-select" th:field="*{newFurniture.furnitureTypeId}">
я вот думаю может в типах мебели и в типах мед оборудования нам не париться и захардкодить их на странице... но я хз пока что

2022-11-27 05:35 UTC, GritsH commented on src/main/resources/templates/admin-lot-id.html
> +                                th:action="@{/admin/lots/delete/{id}(id=${auction.lot.id})}">
да хватит ставить ссылки сабмитам 
я так по рукам начну бить

2022-11-27 05:35 UTC, GritsH commented on src/main/resources/templates/lot-details.html
> +                                th:action="@{/active-auctions/lot/{id}(id=${foundAuction.lot.id})/participate}">
ААААААААА скока можно.........

2022-11-27 05:38 UTC, GritsH commented
если работает, можешь лишний закомментированный код удалить 
НЕ СТАВЬ ССЫЛКИ САБМИТУ, ХВАТИТ, ОНА ДОЛЖНА СОЯТЬ ТОЛЬКО В ФОРМЕ
сделай th: each для дроп дауна в хедере

2022-11-29 05:01 UTC, GritsH commented on src/main/resources/templates/clothes-page.html
> +
когда-нибудь я увижу тут each

2022-11-29 08:47 UTC, GritsH commented on src/main/resources/templates/jewelry-page.html
> +                    <select class="jewelry-precious-stones" id="jewelryPreciousStone"
добавить атрибут name="jewelryPreciousStone"

2022-11-29 08:47 UTC, GritsH commented on src/main/resources/templates/jewelry-page.html
> +                        <option>yes</option>
наверно можно добавить просто value="true/false"

2022-12-04 08:27 UTC, GritsH approved these changes

2022-12-04 08:28 UTC, merged